### PR TITLE
Add locale ca_ES (Catalan)

### PR DESCRIPTION
**Pull request by aaronplanell**

### CODE REVIEW

**Comment by aaronplanell** [comment]
It has no sense. It fails at the:
```
rc-tools run lint
```
But not in my file. It's only a locale file.

**Comment by aaronplanell** [comment]
In fact, it fails at the:
```
const { tsCompiledDir } = require('./constants');
```
But the problem it's not my file. It's only a locale file.

**Comment by aaronplanell** [comment]
Maybe @yiminghe can give more information about the problem :+1:

**Comment by yiminghe** [comment]
travis node version needs to upgrade

**Comment by aaronplanell** [comment]
Perfect! I will make a new pull request of my branch for correcting travis and for correcting a spelling mistake. Thanks a lot @yiminghe !!!

**Pull request merged**
