### PR TITLE
add rc-calendar-selected-week class name

### PR DESCRIPTION
**Pull request by dmitriyK1**
Mark currently selected week <tr> to allow custom styling of whole row.

### CODE REVIEW

**Comment by benjycui** [comment]
This name is confused.

**Comment by dmitriyK1** [comment]
What better name can you suggest so I can refactor current name?

I have picked `selected-week` because it's a className for a "tr" element that is applied when you select a day in a row by clicking on it ("td" cell is using 'selected-day' className, so I've chosen 'selected-week' for row)

**Comment by benjycui** [comment]
`selected-week` make conflict with https://github.com/react-component/calendar/issues/212

**Comment by dmitriyK1** [comment]
I see, yes this is definitely could be a problem
How about rc-calendar-active-week then?

**Comment by benjycui** [comment]
> How about rc-calendar-active-week then?

👍

**Comment by dmitriyK1** [comment]
Thanks for feedback, I've updated sources.

**Comment by benjycui** [comment]
Waiting for https://github.com/react-component/calendar/pull/232, then I will publish a minor version.

**Comment by dmitriyK1** [comment]
Ok, thanks!

**Pull request merged**
