### PR TITLE
#13196 - fixed wrong locale format

### PR DESCRIPTION
**Pull request by gurungrahul2**
All locales don't follow any same format, this PR made a standard format of all
locales.

### CODE REVIEW

**Comment by gurungrahul2** [comment]
https://github.com/ant-design/ant-design/issues/13196 @afc163

**Comment by gurungrahul2** [comment]
@afc163 what do you have to say about this one ?

**Comment by sbusch** [comment]
PR should be closed, see discussion in https://github.com/ant-design/ant-design/issues/13196

**Comment by afc163** [comment]
image

Maybe you should argue with @RickLucassen like #13196 described.

**Pull request closed without merging**
