### PR TITLE
ru locale

### PR DESCRIPTION
**Pull request by plandem**

### CODE REVIEW

**Comment by yiminghe** [comment]
file name should be ru_RU?

**Comment by plandem** [comment]
Yep.

I will translate rest components soon(after integration at admin panel), still need some time. So i will commit more if you want.

-- 
Andrey Gayvoronsky
Sent with Airmail

On 20 Feb 2016 at 13:01:29, yiminghe (notifications@github.com) wrote:

file name should be ru_RU?

**Comment by yiminghe** [comment]
I have merged other prs from gregorian-calendar, I mean in this pr you should change `src/locale/ru-RU.js` to `src/locale/ru_RU.js`

**Comment by yiminghe** [comment]
does not pass lint: `npm run lint`

**Pull request merged**
