### PR TITLE
 FR locale correction for "dateSelect"

### PR DESCRIPTION
**Pull request by shye0000**
Change fr locale for "dateSelect" from 'Sélectionner l\'heure' to 'Sélectionner la date'

### CODE REVIEW

**Comment by shye0000** [comment]
Is it normal that it builds with a failling spashot test?

**Comment by yesmeck** [comment]
@shye0000 You can update snapshot with `npm run text -- -u` and commit the changes, thanks.

**Comment by shye0000** [comment]
@yesmeck Hi, actually, we are developping a french application with ant design, so this little bug of translation is kind of important for our project. Could you please tell me what should I do to make this PR can be accepted please?

**Comment by shye0000** [comment]
@yesmeck ah, ok, I saw in the last version it's been corrected, I will close this PR, Thanks

**Pull request closed without merging**
