### PR TITLE
auto focus on calendar input when opening picker

### PR DESCRIPTION
**Pull request by onlyann**
The current behaviour of the picker is that in order to enter a date manually, one has to click on the picker input twice.

This PR changes the behaviour of the picker to focus the `DateInput` input element instead.

### CODE REVIEW

**Comment by onlyann** [comment]
This should fix ant-design/ant-design#11848

**Comment by mischa-s** [comment]
That lovely moment when you are confused about trying to use a module and the pull request exists to fix exactly what you are working on :heart_eyes: ... now just gotta wait for the merge :angel:

**Comment by onlyann** [comment]
> Any status on this? I've had some users requesting this behavior. Would be happy to help if there is anything that needs doing to get this merged.

Hey @zombieJ ! Would you kindly review the PR when you find the time. Thanks in advance!

**Comment by zombieJ** [comment]
Hi, thanks for PR and sorry for delay.
Currently picker input support direction key operation to change the date in panel. Apply the auto focus, we should also support user to handle the direction key. (Maybe, tap `tab` to focus on the panel to enable it):
kapture 2018-12-14 at 14 41 43

**Comment by onlyann** [comment]
> Hi, thanks for PR and sorry for delay.
> Currently picker input support direction key operation to change the date in panel. Apply the auto focus, we should also support user to handle the direction key. (Maybe, tap `tab` to focus on the panel to enable it):
> kapture 2018-12-14 at 14 41 43

Thank you for the feedback @zombieJ .
Yes, that is one way to do it. 
One drawback is that it then forces the user to tab twice to move out of the date picker.

Instead of tabbing to the panel, direction keys could be handled even if the date input is in focus, effectively removing the `input` target short-circuit in the calendar `onKeyDown`. 
It would remove the ability to move the text cursor on the input. 

Thoughts?

**Comment by zombieJ** [comment]
@onlyann, thanks for adjust. Currently I test left & right operation in input. Panel works but cursor in input not work:
kapture 2018-12-17 at 12 10 29

**Comment by onlyann** [comment]
@zombieJ . Yes, this is what I meant by

> It would remove the ability to move the text cursor on the input.

I am not sure it would make too much sense to have the left/right arrows to move both the input cursor and the panel.

**Comment by zombieJ** [comment]
hi @onlyann ,
It needn't move both of them. Just input auto focus and tab to focus on panel operation. User still can shift + tab back to input.

**Comment by onlyann** [comment]
@zombieJ I added a `focusablePanel` flag to the `Calendar` instead. 
It's been enabled on one of the antd-calendar examples. 
Let me know if something else needs to be done.

🎄 🎁

**Comment by zombieJ** [comment]
wow! That's wonderful!
Could we make it as default behavior instead of additional prop `focusablePanel`?

**Comment by onlyann** [comment]
@zombieJ I  added a default of `true` to `focusablePanel`.

I personally find it useful to expose it as a prop so that it can be switched to `false`, effectively making it a single Tab key stroke to move in and out of the Calendar component.

**Comment by zombieJ** [comment]
OPS. Conflict since this PR: https://github.com/react-component/calendar/pull/470

**Pull request merged**
