### PR TITLE
fix ant-design/issues/10397

### PR DESCRIPTION
**Pull request by Veveue**
http://github.com/ant-design/ant-design/issues/10397

### CODE REVIEW

**Comment by afc163** [comment]
Could you add test case?

**Comment by Veveue** [comment]
> Could you add test case?

https://github.com/Veveue/calendar.git
http://localhost:8002/examples/antd-calendar.html

**Comment by Veveue** [comment]
> Could you add test case?

ok

**Comment by afc163** [comment]
@Veveue

**Comment by Veveue** [comment]
> @Veveue

?

**Comment by yoyo837** [comment]
Conflict @Veveue

**Pull request closed without merging**
