### PR TITLE
adding onBlur property to RangeCalendar component

### PR DESCRIPTION
**Pull request by willdunlop**
Hi, 
I have added an onBlur property for the range calendar component. If no prop is provided, then by default no action will be taken when the component undergoes a blur.

### CODE REVIEW

**Comment by willdunlop** [comment]
Will quickly resolve the drop in coverage

**Comment by em0ney** [comment]
@benjycui - any progress on this one?

**Comment by benjycui** [comment]
User case?

**Comment by em0ney** [comment]
Being able to close the calendar component when the user clicks away

**Comment by benjycui** [comment]
> Being able to close the calendar component when the user clicks away

You don't need this feature, just follow http://react-component.github.io/calendar/examples/antd-calendar.html

**Comment by willdunlop** [comment]
Hi mate,
We are using the range calendar component rather than the one you linked us too. 
We have it implemented as part of a drop down menu with various different date filtering options. The goal is to hide the range calendar when the user clicks away from the component or the drop down menu. Looking at the provided example, I've not been able to see a way to achieve this.

**Comment by benjycui** [comment]
> We are using the range calendar component rather than the one you linked us too.

They are the same. Actually, you should not listen to `onBlur` to hide RangeCalendar, just listen to document[onClick] and compare the click target.

**Pull request closed without merging**
