### PR TITLE
Expose hideDateInput property in RangeCalendar & CalendarPart

### PR DESCRIPTION
**Pull request by razzmatazz**
This allows hiding date input in calendar panels of RangeCalendar component too

### CODE REVIEW

**Comment by yesmeck** [comment]
I think we should name it `showDateInput`, because we already have `showDateInput` for `Calendar`.

**Comment by razzmatazz** [comment]
I thought about using `showDateInput` too, but then I realized it would break things by hiding datetime inputs in existing app code.

**Comment by yesmeck** [comment]
@razzmatazz We can set it default to `true`.

**Comment by razzmatazz** [comment]
I am probably not that knowledgeable about react to realize myself a way how to do this (true by default).

Say we if we have a boolean property and react code variants:
 a) `<Component property={false} />` 
 b) `<Component property={true} />` 
 c) `<Component />` 

What is the expected (canonical) behaviour of `c)` ? And is is normal for user to expect `a)` and `b)` to be the same thing (have the same behaviour)? I realize it compiles down to an empty property object and that props object is passed to `React.createElement()` and I can check on props.property === undefined, but it is the semantics that bother me..

**Comment by yesmeck** [comment]
We can give `showDateInput` a default value like `Calendar` [does](https://github.com/react-component/calendar/blob/master/src/Calendar.jsx#L84).

**Comment by razzmatazz** [comment]
Ok, thanks. Will refactor

**Comment by razzmatazz** [comment]
Ok, I renamed hideDateInput to showDateInput and it will have the default value of `true` now.

**Comment by yesmeck** [comment]
Clear button should be hidden as well I think.

**Comment by razzmatazz** [comment]
Oh.. btw, I could not figure out how can I build the lib for myself from the sources (i.e. just cloning the repo and referencing it from npm did not work (obviously)).

What is the standard procedure to build the lib and reference it from your project to test it w/o making a new release?

**Comment by yesmeck** [comment]
You can run `npm run compile` to build source files to 'lib' dir.

**Comment by yesmeck** [comment]
Hmm, since `showClear` is default to `false`, we don't need handle clear button in this PR. Will merge it.

**Comment by yesmeck** [comment]
Thanks!

**Pull request merged**
