### PR TITLE
Added firstDayOfWeek option

### PR DESCRIPTION
**Pull request by dbachko**
Adds an option to set the first day of the week in the Calendar.

### CODE REVIEW

**Comment by yiminghe** [comment]
set locale for gregorian-calendar

https://github.com/yiminghe/gregorian-calendar

**Comment by dbachko** [comment]
What about if user wants Wednesday or Friday to be the first day of the week?

**Comment by yiminghe** [comment]
```js
var date = new GregorianCalendar(assign(require('gregorian-calendar/lib/locale/zh-cn'),{
firstDayOfWeek:2
})); 
date.setTime(+new Date());
<Calendar defaultValue={date} />
```

**Comment by barroudjo** [comment]
For future people encountering this issue, since the dependency has changed from gregorianCalendar to Moment, here is the new way to solve the problem, configure Moment so that monday (or the day that you want) is the first day of the week:

````javascript
moment.updateLocale('en', {
  week: {
    dow: 1,
  },
})

**Pull request closed without merging**
