### PR TITLE
fix(Picker): merge two focus

### PR DESCRIPTION
**Pull request by Yangzhedi**
fix [#11249](https://github.com/ant-design/ant-design/issues/11249)
merge two focus into one focus

### CODE REVIEW

**Comment by zombieJ** [comment]
We should handle `onFocus` instead of change focus target...

**Comment by Yangzhedi** [comment]
😂

**Comment by Yangzhedi** [comment]
`onFocus` is bind on `span` which wrapped Picker, 
https://github.com/ant-design/ant-design/blob/master/components/date-picker/createPicker.tsx#L246
 `onFocus={props.onFocus}` , how to merge the focus ?

**Comment by zombieJ** [comment]
`onFocus = this.onFocus` and do wrap logic.

**Pull request closed without merging**
