### PR TITLE
Rearrange getEndValue logic

### PR DESCRIPTION
**Pull request by susiwen8**
https://github.com/ant-design/ant-design/issues/16215
@zombieJ Regarding this bug, I found the logic in getEndValue has something to discuss. I'm not sure the way I did is the best way to do.

### CODE REVIEW

**Comment by susiwen8** [comment]
Hi @zombieJ Could you review this PR?

**Comment by zombieJ** [comment]
Sorry for delay. Let me handle this.

**Comment by zombieJ** [comment]
Seems add `showTimePicker` check at the last `if statement` in the `getEndValue` is enough to fix this?
https://github.com/react-component/calendar/blob/master/src/RangeCalendar.js#L480

**Comment by susiwen8** [comment]
@zombieJ Do you mean like this?
Screen Shot 2019-04-29 at 10 15 43

but one test failed

**Comment by zombieJ** [comment]
I see it. Let me check why this test failed. Thanks~

**Comment by zombieJ** [comment]
This statement is use to check date mode panel make sure always diff one month. For the time panel it's also mode as `date`, we should skip the `showTimePicker`:
```diff
if (
- showTimePicker &&
+  !showTimePicker &&
  panelTriggerSource !== 'end' &&
  mode[0] === 'date' &&
  mode[1] === 'date' &&
  endValue.isSame(value[0], 'month')
) {
  endValue = endValue.clone().add(1, 'month');
}
```

**Comment by susiwen8** [comment]
@zombieJ I see, I close this PR and open a new one

**Pull request closed without merging**
