### PR TITLE
增加多选日期功能

### PR DESCRIPTION
**Pull request by hengkx**
image

#https://github.com/ant-design/ant-design/issues/4447

### CODE REVIEW

**Comment by hengkx** [comment]
预览地址 https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html
因为在基础库里面 所以没有调整 UI

**Comment by zombieJ** [comment]
This pull request **introduces 1 alert** when merging 44dc6eaf57a0c92084a1dc9d1daf26964fc70acf into 050cd828d3e76399c00ee8f937c5402a9205cd44 - [view on LGTM.com](https://lgtm.com/projects/g/react-component/calendar/rev/pr-a7f476fdc93fb31eb4a9c73fa58a488fa6d1fb73)

**new alerts:**

* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by hengkx** [comment]
@zombieJ 这个 检测 不太对
image  有在使用，其余的 移除了

**Comment by zombieJ** [comment]
This pull request **introduces 1 alert** and **fixes 4** when merging 361a41c2bf2b3810d08b0e621834a8fbcc91164e into 050cd828d3e76399c00ee8f937c5402a9205cd44 - [view on LGTM.com](https://lgtm.com/projects/g/react-component/calendar/rev/pr-55d0b53792c27be8e878f610f20fe951ffb636bd)

**new alerts:**

* 1 for Unused or undefined state property

**fixed alerts:**

* 4 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by zombieJ** [comment]
This pull request **fixes 4 alerts** when merging 83073383e4636c939a39dc7e755a9ab46a342cd4 into 050cd828d3e76399c00ee8f937c5402a9205cd44 - [view on LGTM.com](https://lgtm.com/projects/g/react-component/calendar/rev/pr-7d062de25a23ea96081a56ab6230d6d803d11207)

**fixed alerts:**

* 4 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by ibcLee** [comment]
> 预览地址 https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html
> 因为在基础库里面 所以没有调整 UI

用9.7.8版本的rc-calendar， onChange的value还是一个moment对象而不是一个数组呢？multiple

**Comment by XinYueXiao** [comment]
> https://deploy-preview-420--rc-calendar.netlify.com/examples/antd-multiple-calendar.html

您好,这个页面404,可以提供下有效的demo的地址吗

**Pull request closed without merging**
