### PR TITLE
feat: handle monthFormat on CalendarHeader selected month value

### PR DESCRIPTION
**Pull request by EscoCreeks**
* fallback on current month formatting

* add new snapshot with a custom local with monthFormat

Hello, while updating rc-calendar we spotted that the month value was in shortFormat.
We would like to handle the monthFormat, the same way as yearFormat is handled, when given in the locale.

Using the calendar with a default locale would give this:
screen shot 2017-11-09 at 22 26 35

Using the calendar with a locale containing  `monthFormat: 'MMMM'` would give this:
screen shot 2017-11-09 at 22 27 49

We added a snapshot in your test with a custom local containing `monthFormat: 'MMMM'`, as a result we have the field `.rc-calendar-month-select` with `March` instead of `Mar`.

### CODE REVIEW

**Comment by EscoCreeks** [comment]
@benjycui did you had time to consider this PR ?

**Comment by benjycui** [comment]
The API's name is confusing.

**Comment by EscoCreeks** [comment]
Seems legit.

What do you think of this alternative ?

```json
monthYearHeader: {
  monthFormat: 'MMMM'
}
```

and then... `locale.monthYearHeader.monthFormat`

**Comment by EscoCreeks** [comment]
@benjycui How do you like it now ? :) It's more specific, and it's related to the `monthYearElement` in which it will be used.

**Comment by EscoCreeks** [comment]
@benjycui Happy new year ! Can you have a look at the new naming ? :)

**Comment by yassine-be** [comment]
@EscoCreeks Hello, i see that short days translation works for you, i doesn't seem to be working for me. only works for the footer botton... i'am probably doing something wrong.
is rc-calendar's locale the one responsible for it ?
if so then should i be doing something else ?

**Comment by EscoCreeks** [comment]
@yassine-be Hello, we are using:
```
import fr_FR from 'rc-calendar/lib/locale/fr_FR'
const locale = { ...fr_FR, monthFormat: 'MMMM' }
```

@benjycui when do you think this will be merged and bumped into a new version ? :)

**Comment by benjycui** [comment]
@yesmeck

**Comment by yesmeck** [comment]
Maybe `monthFormat` isn't the best name, but we already have `yearFormat` for year formatting, `dayFormat` from day formatting, I thinks we should keep this tradition？

**Comment by EscoCreeks** [comment]
@yesmeck Deal.

**Comment by zhaolc90** [comment]
Is this 'monthFormat' in the release 9.6.0 or when will be?

**Comment by rpellerin** [comment]
It is not in 9.6.0. But like you, I'm wondering when it will be released. This is a much needed feature!

**Comment by DeadcatDev** [comment]
Will it work also on range-callender guys? Really need this features alike "day/month/yearFormat". Regards

**Pull request merged**
