### PR TITLE
Date input fix

### PR DESCRIPTION
**Pull request by pavelmazurov1**
Fixed wrong carriage behaviour

---

Edit: 

Close: #320

### CODE REVIEW

**Comment by benjycui** [comment]
What are you going to fix? 
Please provide a re-producible demo: http://codepen.io/benjycui/pen/jBbdLZ?editors=0010

**Comment by yesmeck** [comment]
Look into this issue. A better fix is put cache into `componentWillUpdate`

```javascript
  componentWillUpdate() {
    this.cachedSelectionStart = this.dateInputInstance.selectionStart;
    this.cachedSelectionEnd = this.dateInputInstance.selectionEnd;
  },
```

**Comment by yesmeck** [comment]
@benjycui Try typing here:

**Comment by yesmeck** [comment]
#322

**Pull request closed without merging**
